Repository mathleite/marvel-application-frontend, pull requests merged in 2019-10, with the labels that each got.

#1 Create initial application structure
  .gitignore
  README.md
  babel.config.js
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  src/App.vue
  src/assets/logo.png
  src/assets/logo.svg
  src/components/HelloWorld.vue
  src/main.js
  src/plugins/vuetify.js
Labels: enhancement

#2 Add Vue Router dependency
  .gitignore
  babel.config.js
  package.json
  src/main.js
Labels: SPRINT 2, enhancement

#3 Create Router structure
  src/main.js
  src/router/index.js
Labels: SPRINT 2, enhancement

#4 Create initial Application router and structure
  README.md
  package-lock.json
  src/App.vue
  src/app/components/.gitkeep
  src/app/router.js
  src/app/views/Welcome/Welcome.route.js
  src/app/views/Welcome/Welcome.view.vue
  src/components/HelloWorld.vue
  src/main.js
  src/router/index.js
Labels: SPRINT 2, enhancement, priority: high

#5 Improve app configuration and create views components
  .editorconfig
  .eslintrc
  babel.config.js
  package-lock.json
  package.json
  public/capitao_america.gif
  public/gatinho.jpg
  public/homem_ferro.gif
  public/hulk.gif
  public/index.html
  public/marvel.ico
  src/app/components/.gitkeep
  src/app/components/Base/BaseHeader.vue
  src/app/components/User/UserProfileHeader.vue
  src/app/components/Welcome/WelcomeGifs.vue
  src/app/mixins/RouterMixin.js
  src/app/router.js
  src/app/views/Characters/Characters.route.js
  src/app/views/Characters/Characters.view.vue
  src/app/views/Welcome/Welcome.route.js
  src/app/views/Welcome/Welcome.view.vue
  src/main.js
Labels: Need rebase, SPRINT 2, enhancement, priority: high

#6 Create dotEnv file
  .env.exemple
  .gitignore
Labels: SPRINT 2, enhancement, priority: normal

#7 Add the Axios dependency and configure the same in the application
  .env.exemple
  .gitignore
  package-lock.json
  package.json
  src/app/AxiosHttpClient.js
  vue.config.js
Labels: Need rebase, SPRINT 2, enhancement, priority: high

#10 updated Welcomeview file
  .gitatributes
  src/app/components/Welcome/WelcomeAppDescription.vue
  src/app/views/Welcome/Welcome.view.vue
Labels: SPRINT 2, enhancement, priority: normal

#11 Create the Characters Model
  src/app/Characters/models/CharacterModel.js
Labels: SPRINT 3, enhancement, priority: normal

#12 Create the Character Service
  src/app/Characters/services/CharacterService.js
Labels: SPRINT 3, enhancement, priority: normal
